/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/simulate': typeof SimulateRoute
  '/sources': typeof SourcesRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/simulate': typeof SimulateRoute
  '/sources': typeof SourcesRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/methodology': typeof MethodologyRoute
  '/simulate': typeof SimulateRoute
  '/sources': typeof SourcesRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/methodology'
    | '/simulate'
    | '/sources'
    | '/sitemap/xml'
    | '/api/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/methodology'
    | '/simulate'
    | '/sources'
    | '/sitemap/xml'
    | '/api/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/methodology'
    | '/simulate'
    | '/sources'
    | '/sitemap/xml'
    | '/api/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  MethodologyRoute: typeof MethodologyRoute
  SimulateRoute: typeof SimulateRoute
  SourcesRoute: typeof SourcesRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  MethodologyRoute: MethodologyRoute,
  SimulateRoute: SimulateRoute,
  SourcesRoute: SourcesRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
